### ISSUE TITLE
[Build Failure] NVIDIA closed kernel modules 610.57.04 fail to build on CachyOS 7.1.8

### ISSUE THREAD

**Issue by Inarizxc** [xddxdd/nix-cachyos-kernel#101]
## Description
The proprietary (closed) NVIDIA kernel module 610.57.04 fails to compile against `linux-cachyos-bore-lto-x86_64-v3-7.1.8`.  
The error is caused by a change in the `gpio_device_get_chip()` signature in Linux 6.15+.

## Environment
- **NixOS**: unstable (rev `ec2d622`)
- **Kernel**: `linux-cachyos-bore-lto-x86_64-v3-7.1.8`
- **NVIDIA package**: `config.boot.kernelPackages.nvidiaPackages.latest` → `610.57.04`
- **Driver mode**: `hardware.nvidia.open = false` (closed)
- **GPU**: GTX 1650 (Turing)
- **Flake input**: `github:xddxdd/nix-cachyos-kernel/release`

## Relevant configuration
```nix
boot.kernelPackages = pkgs.cachyosKernels.linuxPackages-cachyos-bore-lto-x86_64-v3;
hardware.nvidia = {
  open = false;
  package = config.boot.kernelPackages.nvidiaPackages.latest;
  modesetting.enable = true;
};
```

## Build log
```
nvidia-kernel-modules> ././common/inc/nv-linux.h:1706:51: error: passing 'const struct gpio_device *' to parameter of type 'struct gpio_device *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
nvidia-kernel-modules>  1706 |     struct gpio_chip *chip = gpio_device_get_chip(gdev);
nvidia-kernel-modules>       |                                                   ^~~~
nvidia-kernel-modules> /nix/store/...-linux-cachyos-bore-lto-x86_64-v3-7.1.8-dev/lib/modules/7.1.8-cachyos-lto/source/include/linux/gpio/driver.h:813:60: note: passing argument to parameter 'gdev' here
nvidia-kernel-modules>   813 | struct gpio_chip *gpio_device_get_chip(struct gpio_device *gdev);

```

### The error occurs in:
- nvidia/nv-platform.c
- nvidia/nv-platform-pm.c
- nvidia/nv-imp.c
- nvidia/nv-bpmp.c
- nvidia/nv-gpio.c
- nvidia/nv-backlight.c
- nvidia/nv-dsi-parse-panel-props.c
- nvidia/nv-ipc-soc.c
